# Define model instructions for ReAct prompting
# The model instruction was borrowed from the ReAct paper with a few minor adjustments.

model_instructions = """
Solve a question answering task with interleaving Thought, Action, Observation steps.
Only use the results from the table provided.
Thought can reason about the current situation,
Observation is understanding relevant information from an Action's output and
Action can be of three types:
(1) <search>entity</search>, which searches the exact entity on table scheme from table `store_df`,
 and returns the column or columns of interested. We already have a dataframe called `store_df`.
 If you cannot find it, you will return some similar columns to search the information from those topics.
(2) <execute>code</execute>, which execute the python code without printing function, assigh the final result to __result__ and returns __result__.
(3) <finish>answer</finish>, which returns the answer from the execution step and finishes the task. If the answer contains a number, please make the number human readable.

"""

# Define table schema for the developer dataframe

table_schema = """
  Here is the table schema for table `store_df`, these description which can help you understand what each column means and the expected entries of the dataframe, can help you search the columns you are looking for.
  The schema description is:

  | Column Name                                       | Description                                                                                                                                                                                                                                                                                                                                                                |
  | :------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------------|
  | `store_id`                                        | The unique identifier of the store. |
  | `store_name`                                      | The name of the store. |
  | `region_code`                                     | The region code where the store is located. |
  | `store_type`                                      | The type of store, such as 'Supermarket' or 'Convenience Store'. |
  | `num_products`                                    | The total number of products sold in the store. |
  | `num_customers_last_28d`                          | The number of customers who visited the store in the last 28 days. |
  | `num_customers_last_180d`                         | The number of customers who visited the store in the last 180 days. |
  | `num_customers_last_365d`                         | The number of customers who visited the store in the last 365 days. |
  | `revenues_last28d`                                | The total revenue generated by the store in the last 28 days. |
  | `revenues_last180d`                               | The total revenue generated by the store in the last 180 days. |
  | `revenues_last365d`                               | The total revenue generated by the store in the last 365 days. |
"""


# Define few-shot examples for in-context learning

examples = """
  Here are an example.

  Question 1
  How much United State stores made in the last 28d?

  Thought 1
  I need to find store that are in US and their corresponding revenue value in the last 28d. I already know the column name for 28d revenue is 'revenues_last28d' and the column for store location is 'region_code'.

  ## Action 1:
  <execute>
  import pandas as pd
  __result__ = store_df[store_df['region_code'] == 'United State']['revenues_last28d'].sum()

  </execute>
  ## Thought 2:
  The code cannot find United State. I will try to find a store in US instead

  ## Action 2:
  <execute>
  import pandas as pd
  __result__ = store_df[store_df['region_code'] == 'US']['revenues_last28d'].sum()

  </execute>

  ## Thought 3:
  The code successfully retrieved the 28d revenue of store in the US.

  ## Action 4:
  <finish> Store in the US made $78,808,584 last 28 days.
"""

# Combine instructions, schema, and examples into the final ReAct prompt
ReAct_prompt = model_instructions + table_schema+ examples

def get_prompt():
    return ReAct_prompt